name = "snipshare"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "snipshare-db"
database_id = "YOUR_D1_DATABASE_ID"
migrations_dir = "drizzle"
